# Generated by Django 4.0.4 on 2022-05-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_project', '0002_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='conf_password',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='conf_password',
            field=models.CharField(max_length=190, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=190, null=True),
        ),
    ]
