# Generated by Django 4.0.4 on 2022-05-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_project', '0003_doctor_conf_password_doctor_password_patient_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=190, null=True)),
                ('password', models.CharField(max_length=190, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signup_doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=190)),
                ('l_name', models.CharField(max_length=190)),
                ('password', models.CharField(max_length=190, null=True)),
                ('conf_password', models.CharField(max_length=190, null=True)),
                ('address', models.CharField(max_length=190, null=True)),
                ('email', models.CharField(max_length=190, null=True)),
                ('phone', models.CharField(max_length=190, null=True)),
                ('age', models.CharField(max_length=190, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signup_patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=190)),
                ('l_name', models.CharField(max_length=190)),
                ('password', models.CharField(max_length=190, null=True)),
                ('conf_password', models.CharField(max_length=190, null=True)),
                ('address', models.CharField(max_length=190, null=True)),
                ('email', models.CharField(max_length=190, null=True)),
                ('phone', models.CharField(max_length=190, null=True)),
                ('age', models.CharField(max_length=190, null=True)),
            ],
        ),
    ]
