# Generated by Django 2.2.14 on 2022-06-30 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graduation_project', '0008_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
